### ISSUE TITLE
Unexpected results from jenkins-job-yaml.erb template

### ISSUE THREAD

**Issue by madAndroid** [puppet-community/puppet-jenkins_job_builder#18]
When I define my config in hiera, the resulting YAML created on disk at `/tmp/jenkins-job_name.yaml` can differ considerably from the structure in hiera, and I sometimes have unexpected results when setting variables in hiera as well; for example, if I create a nested field with a literal `"`, it doesn't get created in the job correctly ..
Example:
```
my_amazing_job:
  delay: 15
  config:
    - job:
        name: my_amazing_job
        description: 'my_amazing_job'
        project-type: freestyle
        scm:
          - git:
              wipe-workspace: false
              credentials-id: 88888888-4444-4444-4444-888888888888
              url: "git@github.com:puppet-community/puppet-jenkins_job_builder.git"
              git-config-name: "User Deploy"
              git-config-email: "user-deploy@domain.com"
              branches:
                - "*/master"
        wrappers:
          - ansicolor
        builders:
          - sbt:
              name: 'sbt'
              actions: "\"release with-defaults\""
              sbt-flags: '-Dsbt.log.noformat=true -Dsbt.override.build.repos=false'

```
results in a config file on disk with:
```
[root@jenkins ~]# cat /tmp/jenkins-my_amazing_job.yaml
---
  - job:
       builders:
        - sbt:
           actions: "release with-defaults\""
           name: "sbt"
           sbt-flags: "-Dsbt.log.noformat=true -Dsbt.override.build.repos=false"
       description: "my_amazing_job"
       name: "my_amazing_job"
       project-type: "freestyle"
       scm:
        - git:
           branches:
             - "*/master"
           credentials-id: "88888888-4444-4444-4444-888888888888"
           git-config-email: "user-deploy@domain.com"
           git-config-name: "User Deploy"
           url: "git@github.com:puppet-community/puppet-jenkins_job_builder.git"
           wipe-workspace: "false"
       wrappers:
         - "ansicolor"
```
The config from hiera is being sorted .. and although this is not a bad thing in itself, the quoted string with escaped `"` is being incorrectly interpreted:
```
"\"release with-defaults\""
```
becomes:
```
"release with-defaults\""
```
and results in a string in the job with only a closing `"`, and not the entire string quoted

A proposed fix would be the one suggested by @choffee in #7  - to use `to_yaml` method in template, instead of the `sort_yaml` which is currently being used
